name: Run tests
on: [push]
jobs:
  Ubuntu-based:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project to runner
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew test
  Windows-based:
    runs-on: windows-latest
    steps:
      - name: Check out project to runner
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: gradle
      - run: .\gradlew.bat test
  MacOS-based:
    runs-on: macos-latest
    steps:
      - name: Check out project to runner
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew test
